-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('home_pb')


local USER = protobuf.Descriptor();
local USER_NICK_FIELD = protobuf.FieldDescriptor();
local USER_LV_FIELD = protobuf.FieldDescriptor();
local USER_EXP_FIELD = protobuf.FieldDescriptor();
local USER_LVUP_EXP_FIELD = protobuf.FieldDescriptor();
local USER_MONEY_FIELD = protobuf.FieldDescriptor();
local USER_G_MONEY_FIELD = protobuf.FieldDescriptor();
local USER_TROPHY_FIELD = protobuf.FieldDescriptor();
local USER_ID_FIELD = protobuf.FieldDescriptor();
local USER_COUNTRY_FIELD = protobuf.FieldDescriptor();
local USER_CITY_FIELD = protobuf.FieldDescriptor();
local CLIENTHOME = protobuf.Descriptor();
local SERVERHOME = protobuf.Descriptor();
local SERVERHOME_USER_FIELD = protobuf.FieldDescriptor();

USER_NICK_FIELD.name = "nick"
USER_NICK_FIELD.full_name = ".Protocol.User.nick"
USER_NICK_FIELD.number = 1
USER_NICK_FIELD.index = 0
USER_NICK_FIELD.label = 2
USER_NICK_FIELD.has_default_value = false
USER_NICK_FIELD.default_value = ""
USER_NICK_FIELD.type = 9
USER_NICK_FIELD.cpp_type = 9

USER_LV_FIELD.name = "lv"
USER_LV_FIELD.full_name = ".Protocol.User.lv"
USER_LV_FIELD.number = 2
USER_LV_FIELD.index = 1
USER_LV_FIELD.label = 2
USER_LV_FIELD.has_default_value = false
USER_LV_FIELD.default_value = 0
USER_LV_FIELD.type = 5
USER_LV_FIELD.cpp_type = 1

USER_EXP_FIELD.name = "exp"
USER_EXP_FIELD.full_name = ".Protocol.User.exp"
USER_EXP_FIELD.number = 3
USER_EXP_FIELD.index = 2
USER_EXP_FIELD.label = 2
USER_EXP_FIELD.has_default_value = false
USER_EXP_FIELD.default_value = 0
USER_EXP_FIELD.type = 5
USER_EXP_FIELD.cpp_type = 1

USER_LVUP_EXP_FIELD.name = "lvup_exp"
USER_LVUP_EXP_FIELD.full_name = ".Protocol.User.lvup_exp"
USER_LVUP_EXP_FIELD.number = 4
USER_LVUP_EXP_FIELD.index = 3
USER_LVUP_EXP_FIELD.label = 2
USER_LVUP_EXP_FIELD.has_default_value = false
USER_LVUP_EXP_FIELD.default_value = 0
USER_LVUP_EXP_FIELD.type = 5
USER_LVUP_EXP_FIELD.cpp_type = 1

USER_MONEY_FIELD.name = "money"
USER_MONEY_FIELD.full_name = ".Protocol.User.money"
USER_MONEY_FIELD.number = 5
USER_MONEY_FIELD.index = 4
USER_MONEY_FIELD.label = 2
USER_MONEY_FIELD.has_default_value = false
USER_MONEY_FIELD.default_value = 0
USER_MONEY_FIELD.type = 5
USER_MONEY_FIELD.cpp_type = 1

USER_G_MONEY_FIELD.name = "g_money"
USER_G_MONEY_FIELD.full_name = ".Protocol.User.g_money"
USER_G_MONEY_FIELD.number = 6
USER_G_MONEY_FIELD.index = 5
USER_G_MONEY_FIELD.label = 2
USER_G_MONEY_FIELD.has_default_value = false
USER_G_MONEY_FIELD.default_value = 0
USER_G_MONEY_FIELD.type = 5
USER_G_MONEY_FIELD.cpp_type = 1

USER_TROPHY_FIELD.name = "trophy"
USER_TROPHY_FIELD.full_name = ".Protocol.User.trophy"
USER_TROPHY_FIELD.number = 7
USER_TROPHY_FIELD.index = 6
USER_TROPHY_FIELD.label = 2
USER_TROPHY_FIELD.has_default_value = false
USER_TROPHY_FIELD.default_value = 0
USER_TROPHY_FIELD.type = 5
USER_TROPHY_FIELD.cpp_type = 1

USER_ID_FIELD.name = "id"
USER_ID_FIELD.full_name = ".Protocol.User.id"
USER_ID_FIELD.number = 8
USER_ID_FIELD.index = 7
USER_ID_FIELD.label = 2
USER_ID_FIELD.has_default_value = false
USER_ID_FIELD.default_value = ""
USER_ID_FIELD.type = 9
USER_ID_FIELD.cpp_type = 9

USER_COUNTRY_FIELD.name = "country"
USER_COUNTRY_FIELD.full_name = ".Protocol.User.country"
USER_COUNTRY_FIELD.number = 9
USER_COUNTRY_FIELD.index = 8
USER_COUNTRY_FIELD.label = 2
USER_COUNTRY_FIELD.has_default_value = false
USER_COUNTRY_FIELD.default_value = ""
USER_COUNTRY_FIELD.type = 9
USER_COUNTRY_FIELD.cpp_type = 9

USER_CITY_FIELD.name = "city"
USER_CITY_FIELD.full_name = ".Protocol.User.city"
USER_CITY_FIELD.number = 10
USER_CITY_FIELD.index = 9
USER_CITY_FIELD.label = 2
USER_CITY_FIELD.has_default_value = false
USER_CITY_FIELD.default_value = ""
USER_CITY_FIELD.type = 9
USER_CITY_FIELD.cpp_type = 9

USER.name = "User"
USER.full_name = ".Protocol.User"
USER.nested_types = {}
USER.enum_types = {}
USER.fields = {USER_NICK_FIELD, USER_LV_FIELD, USER_EXP_FIELD, USER_LVUP_EXP_FIELD, USER_MONEY_FIELD, USER_G_MONEY_FIELD, USER_TROPHY_FIELD, USER_ID_FIELD, USER_COUNTRY_FIELD, USER_CITY_FIELD}
USER.is_extendable = false
USER.extensions = {}
CLIENTHOME.name = "ClientHome"
CLIENTHOME.full_name = ".Protocol.ClientHome"
CLIENTHOME.nested_types = {}
CLIENTHOME.enum_types = {}
CLIENTHOME.fields = {}
CLIENTHOME.is_extendable = false
CLIENTHOME.extensions = {}
SERVERHOME_USER_FIELD.name = "user"
SERVERHOME_USER_FIELD.full_name = ".Protocol.ServerHome.user"
SERVERHOME_USER_FIELD.number = 1
SERVERHOME_USER_FIELD.index = 0
SERVERHOME_USER_FIELD.label = 2
SERVERHOME_USER_FIELD.has_default_value = false
SERVERHOME_USER_FIELD.default_value = nil
SERVERHOME_USER_FIELD.message_type = USER
SERVERHOME_USER_FIELD.type = 11
SERVERHOME_USER_FIELD.cpp_type = 10

SERVERHOME.name = "ServerHome"
SERVERHOME.full_name = ".Protocol.ServerHome"
SERVERHOME.nested_types = {}
SERVERHOME.enum_types = {}
SERVERHOME.fields = {SERVERHOME_USER_FIELD}
SERVERHOME.is_extendable = false
SERVERHOME.extensions = {}

ClientHome = protobuf.Message(CLIENTHOME)
ServerHome = protobuf.Message(SERVERHOME)
User = protobuf.Message(USER)

