-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local result_pb = require("result_pb")
module('player_pb')


local SERVERPLAYERLVUP = protobuf.Descriptor();
local SERVERPLAYERLVUP_OLD_LV_FIELD = protobuf.FieldDescriptor();
local SERVERPLAYERLVUP_NEW_LV_FIELD = protobuf.FieldDescriptor();

SERVERPLAYERLVUP_OLD_LV_FIELD.name = "old_lv"
SERVERPLAYERLVUP_OLD_LV_FIELD.full_name = ".Protocol.ServerPlayerLvup.old_lv"
SERVERPLAYERLVUP_OLD_LV_FIELD.number = 1
SERVERPLAYERLVUP_OLD_LV_FIELD.index = 0
SERVERPLAYERLVUP_OLD_LV_FIELD.label = 2
SERVERPLAYERLVUP_OLD_LV_FIELD.has_default_value = false
SERVERPLAYERLVUP_OLD_LV_FIELD.default_value = 0
SERVERPLAYERLVUP_OLD_LV_FIELD.type = 5
SERVERPLAYERLVUP_OLD_LV_FIELD.cpp_type = 1

SERVERPLAYERLVUP_NEW_LV_FIELD.name = "new_lv"
SERVERPLAYERLVUP_NEW_LV_FIELD.full_name = ".Protocol.ServerPlayerLvup.new_lv"
SERVERPLAYERLVUP_NEW_LV_FIELD.number = 2
SERVERPLAYERLVUP_NEW_LV_FIELD.index = 1
SERVERPLAYERLVUP_NEW_LV_FIELD.label = 2
SERVERPLAYERLVUP_NEW_LV_FIELD.has_default_value = false
SERVERPLAYERLVUP_NEW_LV_FIELD.default_value = 0
SERVERPLAYERLVUP_NEW_LV_FIELD.type = 5
SERVERPLAYERLVUP_NEW_LV_FIELD.cpp_type = 1

SERVERPLAYERLVUP.name = "ServerPlayerLvup"
SERVERPLAYERLVUP.full_name = ".Protocol.ServerPlayerLvup"
SERVERPLAYERLVUP.nested_types = {}
SERVERPLAYERLVUP.enum_types = {}
SERVERPLAYERLVUP.fields = {SERVERPLAYERLVUP_OLD_LV_FIELD, SERVERPLAYERLVUP_NEW_LV_FIELD}
SERVERPLAYERLVUP.is_extendable = false
SERVERPLAYERLVUP.extensions = {}

ServerPlayerLvup = protobuf.Message(SERVERPLAYERLVUP)

