-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('rank_pb')


local CLIENTRANK = protobuf.Descriptor();
local SERVERRANK = protobuf.Descriptor();
local SERVERRANK_USER = protobuf.Descriptor();
local SERVERRANK_USER_NICK_FIELD = protobuf.FieldDescriptor();
local SERVERRANK_USER_TROPHY_FIELD = protobuf.FieldDescriptor();
local SERVERRANK_USER_LV_FIELD = protobuf.FieldDescriptor();
local SERVERRANK_USER_RANK_FIELD = protobuf.FieldDescriptor();
local SERVERRANK_USERS_FIELD = protobuf.FieldDescriptor();

CLIENTRANK.name = "ClientRank"
CLIENTRANK.full_name = ".Protocol.ClientRank"
CLIENTRANK.nested_types = {}
CLIENTRANK.enum_types = {}
CLIENTRANK.fields = {}
CLIENTRANK.is_extendable = false
CLIENTRANK.extensions = {}
SERVERRANK_USER_NICK_FIELD.name = "nick"
SERVERRANK_USER_NICK_FIELD.full_name = ".Protocol.ServerRank.User.nick"
SERVERRANK_USER_NICK_FIELD.number = 1
SERVERRANK_USER_NICK_FIELD.index = 0
SERVERRANK_USER_NICK_FIELD.label = 2
SERVERRANK_USER_NICK_FIELD.has_default_value = false
SERVERRANK_USER_NICK_FIELD.default_value = ""
SERVERRANK_USER_NICK_FIELD.type = 9
SERVERRANK_USER_NICK_FIELD.cpp_type = 9

SERVERRANK_USER_TROPHY_FIELD.name = "trophy"
SERVERRANK_USER_TROPHY_FIELD.full_name = ".Protocol.ServerRank.User.trophy"
SERVERRANK_USER_TROPHY_FIELD.number = 2
SERVERRANK_USER_TROPHY_FIELD.index = 1
SERVERRANK_USER_TROPHY_FIELD.label = 2
SERVERRANK_USER_TROPHY_FIELD.has_default_value = false
SERVERRANK_USER_TROPHY_FIELD.default_value = 0
SERVERRANK_USER_TROPHY_FIELD.type = 5
SERVERRANK_USER_TROPHY_FIELD.cpp_type = 1

SERVERRANK_USER_LV_FIELD.name = "lv"
SERVERRANK_USER_LV_FIELD.full_name = ".Protocol.ServerRank.User.lv"
SERVERRANK_USER_LV_FIELD.number = 3
SERVERRANK_USER_LV_FIELD.index = 2
SERVERRANK_USER_LV_FIELD.label = 2
SERVERRANK_USER_LV_FIELD.has_default_value = false
SERVERRANK_USER_LV_FIELD.default_value = 0
SERVERRANK_USER_LV_FIELD.type = 5
SERVERRANK_USER_LV_FIELD.cpp_type = 1

SERVERRANK_USER_RANK_FIELD.name = "rank"
SERVERRANK_USER_RANK_FIELD.full_name = ".Protocol.ServerRank.User.rank"
SERVERRANK_USER_RANK_FIELD.number = 4
SERVERRANK_USER_RANK_FIELD.index = 3
SERVERRANK_USER_RANK_FIELD.label = 2
SERVERRANK_USER_RANK_FIELD.has_default_value = false
SERVERRANK_USER_RANK_FIELD.default_value = 0
SERVERRANK_USER_RANK_FIELD.type = 5
SERVERRANK_USER_RANK_FIELD.cpp_type = 1

SERVERRANK_USER.name = "User"
SERVERRANK_USER.full_name = ".Protocol.ServerRank.User"
SERVERRANK_USER.nested_types = {}
SERVERRANK_USER.enum_types = {}
SERVERRANK_USER.fields = {SERVERRANK_USER_NICK_FIELD, SERVERRANK_USER_TROPHY_FIELD, SERVERRANK_USER_LV_FIELD, SERVERRANK_USER_RANK_FIELD}
SERVERRANK_USER.is_extendable = false
SERVERRANK_USER.extensions = {}
SERVERRANK_USER.containing_type = SERVERRANK
SERVERRANK_USERS_FIELD.name = "users"
SERVERRANK_USERS_FIELD.full_name = ".Protocol.ServerRank.users"
SERVERRANK_USERS_FIELD.number = 1
SERVERRANK_USERS_FIELD.index = 0
SERVERRANK_USERS_FIELD.label = 3
SERVERRANK_USERS_FIELD.has_default_value = false
SERVERRANK_USERS_FIELD.default_value = {}
SERVERRANK_USERS_FIELD.message_type = SERVERRANK_USER
SERVERRANK_USERS_FIELD.type = 11
SERVERRANK_USERS_FIELD.cpp_type = 10

SERVERRANK.name = "ServerRank"
SERVERRANK.full_name = ".Protocol.ServerRank"
SERVERRANK.nested_types = {SERVERRANK_USER}
SERVERRANK.enum_types = {}
SERVERRANK.fields = {SERVERRANK_USERS_FIELD}
SERVERRANK.is_extendable = false
SERVERRANK.extensions = {}

ClientRank = protobuf.Message(CLIENTRANK)
ServerRank = protobuf.Message(SERVERRANK)
ServerRank.User = protobuf.Message(SERVERRANK_USER)

