-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local result_pb = require("result_pb")
module('sys_pb')


local SERVERMSG = protobuf.Descriptor();
local SERVERMSG_MSG_FIELD = protobuf.FieldDescriptor();
local CLIENTHEARTBEAT = protobuf.Descriptor();
local SERVERHEARTBEAT = protobuf.Descriptor();

SERVERMSG_MSG_FIELD.name = "msg"
SERVERMSG_MSG_FIELD.full_name = ".Protocol.ServerMsg.msg"
SERVERMSG_MSG_FIELD.number = 1
SERVERMSG_MSG_FIELD.index = 0
SERVERMSG_MSG_FIELD.label = 2
SERVERMSG_MSG_FIELD.has_default_value = false
SERVERMSG_MSG_FIELD.default_value = ""
SERVERMSG_MSG_FIELD.type = 9
SERVERMSG_MSG_FIELD.cpp_type = 9

SERVERMSG.name = "ServerMsg"
SERVERMSG.full_name = ".Protocol.ServerMsg"
SERVERMSG.nested_types = {}
SERVERMSG.enum_types = {}
SERVERMSG.fields = {SERVERMSG_MSG_FIELD}
SERVERMSG.is_extendable = false
SERVERMSG.extensions = {}
CLIENTHEARTBEAT.name = "ClientHeartbeat"
CLIENTHEARTBEAT.full_name = ".Protocol.ClientHeartbeat"
CLIENTHEARTBEAT.nested_types = {}
CLIENTHEARTBEAT.enum_types = {}
CLIENTHEARTBEAT.fields = {}
CLIENTHEARTBEAT.is_extendable = false
CLIENTHEARTBEAT.extensions = {}
SERVERHEARTBEAT.name = "ServerHeartbeat"
SERVERHEARTBEAT.full_name = ".Protocol.ServerHeartbeat"
SERVERHEARTBEAT.nested_types = {}
SERVERHEARTBEAT.enum_types = {}
SERVERHEARTBEAT.fields = {}
SERVERHEARTBEAT.is_extendable = false
SERVERHEARTBEAT.extensions = {}

ClientHeartbeat = protobuf.Message(CLIENTHEARTBEAT)
ServerHeartbeat = protobuf.Message(SERVERHEARTBEAT)
ServerMsg = protobuf.Message(SERVERMSG)

